### ISSUE TITLE
DockerfileTest fails: No PostgreSQL, Node and Yarn sections generated

### ISSUE THREAD

**Issue by oliverklee** [evilmartians/ruby-on-whales#14]
https://github.com/evilmartians/ruby-on-whales/runs/5660599326?check_suite_focus=true

According to the test run in https://github.com/evilmartians/ruby-on-whales/runs/5660599326?check_suite_focus=true, the `Dockerfile` generated  in the tests does not have the sections that are within conditions that depend on the variables `postgres_version`, `node_version` and `yarn_version`, causing the test to fail.

I don't know whether the generator is broken or whether the it is the test.

**Comment by palkan** [comment]
That's the tests issue.
I haven't figured out how to resolve these random failures (especially on CI), yet 😞
