### ISSUE TITLE
XDG_DATA_HOME compose env variable location?

### ISSUE THREAD

**Issue by clinejj** [evilmartians/ruby-on-whales#18]
We're implementing a version of the docker setup outlined here for our own development, and was curious if the following was intentional:

The `rails_cache` volume is set to `/app/tmp/cache`:
https://github.com/evilmartians/ruby-on-whales/blob/f6f268d8769b55d9955cac4b00be66caeaf7014a/generator/compose.yml.tt#L32

The `XDG_DATA_HOME` environment variable is set to `/app/tmp/caches` (plural):
https://github.com/evilmartians/ruby-on-whales/blob/f6f268d8769b55d9955cac4b00be66caeaf7014a/generator/compose.yml.tt#L62

Is `XDG_DATA_HOME` meant to be on the `rails_cache` volume? or a different directory with a too-close name?

**Comment by palkan** [comment]
It's a typo 🙂 Fixed
